### ISSUE TITLE
Increment/Decrement the number of windows in the master area

### ISSUE THREAD

**Issue by noreun** [gfxmonk/shellshape#112]
This was so useful in bluetile and seams to be so simple to implement: 

```
     Win+,           Increment the number of windows in the master area
     Win+.           Decrement the number of windows in the master area
```

This way we can make 4x4 grids, and actually any configuration we want.

**Comment by hThoreau** [comment]
Hi @timbertson 
I've got only the command to further divide the main area to work. The command to decrease the number of divisions, even when assigned to a shortcut that, for other commands, normally would be work, do not. If not to get this command to be functional, I would like to, at least, be able to reset the layout to its default configuration.

Thanks for any help provided.

**Comment by timbertson** [comment]
Fair point @hThoreau; done in ae417fcf1d810846cf19d9349e365093e8c91227
