### ISSUE TITLE
Window positions messed up after screen unlock

### ISSUE THREAD

**Issue by ghost** [gfxmonk/shellshape#145]
Title says it all. Using latest gnome on ArchLinux (x86_64 if that makes any sense). Even if I'm not using shellshape's tile function and the extensio is only left to be enabled, this still happens. Somehow extension effects windows positions even if you don't use extension itself.

**Comment by emempi** [comment]
I'm running shellshape version 15 and indeed see this same behavior -- after locking/unlocking of the screen, window sizes are messed up (maybe they are set to the sizes they originally had when they appeared first time? ). The problem happens only on desktops with floating layout; tiled desktops seem to play nice now.

**Comment by gfxmonk** [comment]
@emempi: thanks for pointing that out, it could definitely be an issue with floating layout. I'm busy for a little while, but I'll try and look into this sometime soon.

**Comment by gfxmonk** [comment]
I'm afraid I couldn't reproduce, @emempi. The tiling code is remembering the position (and restoring it) after locking / unlocking for me.

**Comment by lpereira** [comment]
If the windows are maximized (even if only vertically-maximized), they're not restored after unlocking the screen. Using Shellshape from GIT, GNOME 3.16.2.

**Comment by svenpilz** [comment]
Maybe it's bit old, but I just started using shellshape (which is asome, btw) and experience the same. When in floating mode with maximized windows, lock and unlock messes up the size of all windows. Seems they are no longer maximized. Got shellshape vom e.g.o and use 3.20 on Arch.
