### ISSUE TITLE
Gnome 3.16 compatibility

### ISSUE THREAD

**Issue by Amxx** [gfxmonk/shellshape#154]
Please update to provide compatibility with gnome 3.16. 
I fell lost without tileable windows

**Comment by wiegraffolles** [comment]
Agreed! This should be a core functionality of GNOME Shell it's so useful...

**Comment by gfxmonk** [comment]
Yup, this was fixed a week ago thanks to @spacepluk (I don't run 3.16 yet myself). I was holding off a release to try and address #149 but I've made a release without those changes for now.

**Comment by wiegraffolles** [comment]
Do we have to use the Zero installer to get it?

**Comment by gfxmonk** [comment]
Until the new version is approved[0], yes. Alternatively, you can git clone & install it locally (instructions in the README). You'll want to install the `3.16` branch, rather than `master`.

[0]: https://extensions.gnome.org/review/4832 (that may not be publicly visible though)

**Comment by wiegraffolles** [comment]
Thanks! 0 is in a really bad state on Arch atm, so I will use the manual method for now.

**Comment by jancr** [comment]
For future googles: you also need to install typescript
and node may be installed by nodejs by your distribution

the following worked for me:
```
ln -s  /usr/bin/nodejs /usr/bin/node
npm install -g typescript
```

**Comment by gfxmonk** [comment]
@jancr I'm surprised at both of those steps. The readme says you need `npm` and `python`, everything else should be taken care of by the build scripts. If you need the `ln` hack, your distro's nodejs / npm may be busted (what distro?). And I'm pretty sure `npm install -g typescript` isn't useful, since the build scripts install and use typescript in the local `./node_modules` folder.

**Comment by spacepluk** [comment]
That's probably a debian-based distro.  On debian I used to compile node from source because the official package is so broken and old :(

If you're on ubuntu there might be a PPA you can use with a more vanilla nodejs package.

**Comment by jancr** [comment]
Yest @spacepluk  I am using debian 9, where node is installed as nodejs
```
nodejs --version
v0.10.38
```
which is the default stretch version (https://packages.debian.org/search?keywords=nodejs), thus debian testing is a major version or two behind :).

@gfxmonk I will admit that installing typescript may not be necessary... as I am not a javascript developer I spend 2 hours of desperation trying out different stuff, and when I did the above 2 things it finally worked... I did not uninstall your addon and npm and try to see if it would work with only the symlink hack... (if if finally ain't broken, dont fix it :))
