### ISSUE TITLE
Add common edge resize

### ISSUE THREAD

**Issue by lightonflux** [gfxmonk/shellshape#158]
If two windows have a common edge and the user resizes one window, then shellshape does not change the other windows. So the windows overlap.

But it would same some work for the user if shellshape would resize the other window too. 

Random example window from the web: 
![Example GIF](http://www.nurgo-software.com/images/AquaSnap/GroupSize.gif)

**Comment by gfxmonk** [comment]
Yup, this is a known issue (see #43 for more discussion)
